---
version: 2.1

executors:
  build-image:
    docker:
      - image: alpine:latest

jobs:
  apply:
    executor: build-image
    steps:
      - checkout
      - run:
          name: Applying Terraform Plan
          command: |
            echo "Apply"

workflows:
  terraform_flow:
    jobs:
      - apply:
          requires:
            - hold
      - hold:
          type: approval
          requires:
            - apply
