version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Terraform plan
          command: |
            echo "plan"
      - run:
          name: Terraform Apply Generate config
          command: |
            echo "If Seconds of now is even then run apply_generated_config.yml else noop"
            if [[ $(expr $(date +%s) % 2) == 0 ]]
            then
            cp .circleci/apply_generated_config.yml .circleci/generated_config.yml
            else
            cp .circleci/noop_generated_config.yml .circleci/generated_config.yml
            fi

      - continuation/continue:
          configuration_path: .circleci/generated_config.yml

workflows:
  setup:
    jobs:
      - setup
