version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Terraform plan
          command: |
            echo "plan"
      - run:
          name: Terraform Apply Generate config
          command: |
            echo "Generate config if apply is due"
            cp .circleci/noapply_generated_config.yml .circleci/generated_config.yml

      - continuation/continue:
          configuration_path: .circleci/generated_config.yml

workflows:
  setup:
    jobs:
      - setup
