version: 2.1

setup: true
executors:
  ubuntu:
    docker:
      - image: ubuntu:latest

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: ubuntu
    steps:
      - checkout
      - run:
          name: Terraform plan
          command: |
            echo "plan"
            apt-get -y update
            apt-get -y install curl jq
      - run:
          name: Terraform Apply Generate config
          command: |
            echo "If Seconds of now is even then run apply_generated_config.yml else noop"
            if [[ $(expr $(date +%s) % 2) == 0 ]]
            then
            cp .circleci/apply_generated_config.yml .circleci/generated_config.yml
            else
            cp .circleci/noop_generated_config.yml .circleci/generated_config.yml
            fi

      - continuation/continue:
          configuration_path: .circleci/generated_config.yml

workflows:
  nightly:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - setup
