---
version: 2.1

executors:
  alpine:
    docker:
      - image: alpine:latest

jobs:
  noop:
    executor: alpine
    steps:
      - run:
          name: apply
          command: |
            echo "noop"

workflows:
  terraform_flow:
    jobs:
      - apply
